Domain,Base Domain,Live,MX Record,Mail Servers,Mail Server Ports Tested,Domain Supports SMTP,Domain Supports SMTP Results,Domain Supports STARTTLS,Domain Supports STARTTLS Results,SPF Record,Valid SPF,SPF Results,DMARC Record,Valid DMARC,DMARC Results,DMARC Record on Base Domain,Valid DMARC Record on Base Domain,DMARC Results on Base Domain,DMARC Policy,DMARC Policy Percentage,DMARC Aggregate Report URIs,DMARC Forensic Report URIs,DMARC Has Aggregate Report URI,DMARC Has Forensic Report URI,Syntax Errors,Debug Info
padovanet.it,padovanet.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: padovanet.it. IN MX, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.padovanet.it., _dmarc.padovanet.it."
egovpadova.comune.padova.it,comune.padova.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: egovpadova.comune.padova.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: egovpadova.comune.padova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: egovpadova.comune.padova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.egovpadova.comune.padova.it., _dmarc.egovpadova.comune.padova.it."
serviziweb5.comune.padova.it,comune.padova.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: serviziweb5.comune.padova.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: serviziweb5.comune.padova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: serviziweb5.comune.padova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.serviziweb5.comune.padova.it., _dmarc.serviziweb5.comune.padova.it."
sso.comune.padova.it,comune.padova.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: sso.comune.padova.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: sso.comune.padova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: sso.comune.padova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.sso.comune.padova.it., _dmarc.sso.comune.padova.it."
posta.comune.padova.it,comune.padova.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: posta.comune.padova.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: posta.comune.padova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: posta.comune.padova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.posta.comune.padova.it., _dmarc.posta.comune.padova.it."
serviziweb4.comune.padova.it,comune.padova.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: serviziweb4.comune.padova.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: serviziweb4.comune.padova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: serviziweb4.comune.padova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.serviziweb4.comune.padova.it., _dmarc.serviziweb4.comune.padova.it."
istanzeonline.comune.padova.it,comune.padova.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: istanzeonline.comune.padova.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: istanzeonline.comune.padova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: istanzeonline.comune.padova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.istanzeonline.comune.padova.it., _dmarc.istanzeonline.comune.padova.it."
cnf.padovanet.it,padovanet.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: cnf.padovanet.it. IN MX, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.cnf.padovanet.it., _dmarc.cnf.padovanet.it."
cartografia.comune.padova.it,comune.padova.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: cartografia.comune.padova.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: cartografia.comune.padova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: cartografia.comune.padova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.cartografia.comune.padova.it., _dmarc.cartografia.comune.padova.it."
meb.comune.padova.it,comune.padova.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: meb.comune.padova.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: meb.comune.padova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: meb.comune.padova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.meb.comune.padova.it., _dmarc.meb.comune.padova.it."
progettogiovani.pd.it,progettogiovani.pd.it,True,False,,,False,,False,,True,True,v=spf1 include:musvc.com ~all,False,False,,False,False,,,,,,False,False,,[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: progettogiovani.pd.it. IN MX
babeleanordest.com,babeleanordest.com,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: babeleanordest.com. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: babeleanordest.com. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: babeleanordest.com. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.babeleanordest.com. IN TXT"
multimedia.padovanet.it,padovanet.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: multimedia.padovanet.it. IN MX, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.multimedia.padovanet.it., _dmarc.multimedia.padovanet.it."
babeleanordest.it,babeleanordest.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: babeleanordest.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: babeleanordest.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: babeleanordest.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.babeleanordest.it. IN TXT"
universidiversi.it,universidiversi.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: universidiversi.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: universidiversi.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: universidiversi.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.universidiversi.it. IN TXT"
estatecarrarese.it,estatecarrarese.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: estatecarrarese.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: estatecarrarese.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: estatecarrarese.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.estatecarrarese.it. IN TXT"
altinatesangaetano.it,altinatesangaetano.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: altinatesangaetano.it. IN MX
discoverpadova.eu,discoverpadova.eu,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: discoverpadova.eu. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: discoverpadova.eu. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: discoverpadova.eu. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.discoverpadova.eu. IN TXT"
padova.cittadiniattivi.net,cittadiniattivi.net,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: padova.cittadiniattivi.net. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padova.cittadiniattivi.net. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padova.cittadiniattivi.net. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.padova.cittadiniattivi.net., _dmarc.padova.cittadiniattivi.net."
babeleanordest.com,babeleanordest.com,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: babeleanordest.com. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: babeleanordest.com. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: babeleanordest.com. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.babeleanordest.com. IN TXT"
capitaledelrunning.it,capitaledelrunning.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: capitaledelrunning.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: capitaledelrunning.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: capitaledelrunning.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.capitaledelrunning.it. IN TXT"
capitalerunning.it,capitalerunning.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: capitalerunning.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: capitalerunning.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: capitalerunning.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.capitalerunning.it. IN TXT"
concorsocorradetti.com,concorsocorradetti.com,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: concorsocorradetti.com. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: concorsocorradetti.com. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: concorsocorradetti.com. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.concorsocorradetti.com. IN TXT"
centroculturalepadova.it,centroculturalepadova.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: centroculturalepadova.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: centroculturalepadova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: centroculturalepadova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.centroculturalepadova.it. IN TXT"
concorsoliricocorradetti.com,concorsoliricocorradetti.com,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: concorsoliricocorradetti.com. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: concorsoliricocorradetti.com. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: concorsoliricocorradetti.com. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.concorsoliricocorradetti.com. IN TXT"
concorsocorradetti.it,concorsocorradetti.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: concorsocorradetti.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: concorsocorradetti.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: concorsocorradetti.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.concorsocorradetti.it. IN TXT"
concorsoliricocorradetti.it,concorsoliricocorradetti.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: concorsoliricocorradetti.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: concorsoliricocorradetti.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: concorsoliricocorradetti.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.concorsoliricocorradetti.it. IN TXT"
cortiliecologici.it,cortiliecologici.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: cortiliecologici.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: cortiliecologici.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: cortiliecologici.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.cortiliecologici.it. IN TXT"
corriperpadova.it,corriperpadova.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: corriperpadova.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: corriperpadova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: corriperpadova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.corriperpadova.it. IN TXT"
discoverpadova.com,discoverpadova.com,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: discoverpadova.com. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: discoverpadova.com. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: discoverpadova.com. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.discoverpadova.com. IN TXT"
discoverpadova.it,discoverpadova.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: discoverpadova.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: discoverpadova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: discoverpadova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.discoverpadova.it. IN TXT"
discoverpadova.org,discoverpadova.org,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: discoverpadova.org. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: discoverpadova.org. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: discoverpadova.org. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.discoverpadova.org. IN TXT"
ipadovaoggi.it,ipadovaoggi.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: ipadovaoggi.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: ipadovaoggi.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: ipadovaoggi.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.ipadovaoggi.it. IN TXT"
ipadovatoday.it,ipadovatoday.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: ipadovatoday.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: ipadovatoday.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: ipadovatoday.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.ipadovatoday.it. IN TXT"
irisadamicorradetti.com,irisadamicorradetti.com,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: irisadamicorradetti.com. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: irisadamicorradetti.com. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: irisadamicorradetti.com. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.irisadamicorradetti.com. IN TXT"
irisadamicorradetti.it,irisadamicorradetti.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: irisadamicorradetti.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: irisadamicorradetti.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: irisadamicorradetti.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.irisadamicorradetti.it. IN TXT"
discoverpadova.net,discoverpadova.net,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: discoverpadova.net. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: discoverpadova.net. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: discoverpadova.net. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.discoverpadova.net. IN TXT"
memory2000.net,memory2000.net,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: memory2000.net. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: memory2000.net. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: memory2000.net. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.memory2000.net. IN TXT"
padovacapitaledelrunning.it,padovacapitaledelrunning.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: padovacapitaledelrunning.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovacapitaledelrunning.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovacapitaledelrunning.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.padovacapitaledelrunning.it. IN TXT"
padovacapitalerunning.it,padovacapitalerunning.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: padovacapitalerunning.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovacapitalerunning.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovacapitalerunning.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.padovacapitalerunning.it. IN TXT"
life-ecocourts.it,life-ecocourts.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: life-ecocourts.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: life-ecocourts.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: life-ecocourts.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.life-ecocourts.it. IN TXT"
padovacultura.it,padovacultura.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: padovacultura.it. IN MX
padovanet.com,padovanet.com,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: padovanet.com. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovanet.com. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovanet.com. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.padovanet.com. IN TXT"
padovanet.org,padovanet.org,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: padovanet.org. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovanet.org. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovanet.org. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.padovanet.org. IN TXT"
padovarun.it,padovarun.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: padovarun.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovarun.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovarun.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.padovarun.it. IN TXT"
padovarunning.it,padovarunning.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: padovarunning.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovarunning.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovarunning.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.padovarunning.it. IN TXT"
discoverpadova.info,discoverpadova.info,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: discoverpadova.info. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: discoverpadova.info. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: discoverpadova.info. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.discoverpadova.info. IN TXT"
padovasmart.it,padovasmart.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: padovasmart.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovasmart.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovasmart.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.padovasmart.it. IN TXT"
runpadova.it,runpadova.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: runpadova.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: runpadova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: runpadova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.runpadova.it. IN TXT"
vocideuropa.net,vocideuropa.net,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: vocideuropa.net. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: vocideuropa.net. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: vocideuropa.net. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.vocideuropa.net. IN TXT"
pernessunmotivo.org,pernessunmotivo.org,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: pernessunmotivo.org. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: pernessunmotivo.org. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: pernessunmotivo.org. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: The DNS response does not contain an answer to the question: _dmarc.pernessunmotivo.org. IN TXT"
yeswebike.it,yeswebike.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: yeswebike.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: yeswebike.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: yeswebike.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.yeswebike.it., _dmarc.yeswebike.it."
aps-advertising.it,aps-advertising.it,True,True,mailftr3.telerete.it,"25, 587, 465",True,"mailftr3.telerete.it:25, mailftr3.telerete.it:587",False,,False,False,,False,False,,False,False,,,,,,False,False,,"[SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: aps-advertising.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: aps-advertising.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.aps-advertising.it., _dmarc.aps-advertising.it."
apsopere.it,apsopere.it,True,True,mailftr3.telerete.it,"25, 587, 465",True,"mailftr3.telerete.it:25, mailftr3.telerete.it:587",False,,False,False,,False,False,,False,False,,,,,,False,False,,"[SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: apsopere.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: apsopere.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.apsopere.it., _dmarc.apsopere.it."
parcheggipadova.it,parcheggipadova.it,True,True,mailftr3.telerete.it,"25, 587, 465",True,"mailftr3.telerete.it:25, mailftr3.telerete.it:587",False,,False,False,,False,False,,False,False,,,,,,False,False,,"[STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 111] Connection refused, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: parcheggipadova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: parcheggipadova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.parcheggipadova.it., _dmarc.parcheggipadova.it."
cremazionepadova.it,cremazionepadova.it,True,True,mailftr3.telerete.it,"25, 587, 465",True,"mailftr3.telerete.it:25, mailftr3.telerete.it:587",False,,False,False,,False,False,,False,False,,,,,,False,False,,"[SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: cremazionepadova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: cremazionepadova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.cremazionepadova.it., _dmarc.cremazionepadova.it."
carsharingpadova.it,carsharingpadova.it,True,True,mailftr3.telerete.it,"25, 587, 465",True,"mailftr3.telerete.it:25, mailftr3.telerete.it:587",False,,False,False,,False,False,,False,False,,,,,,False,False,,"[SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: carsharingpadova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: carsharingpadova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.carsharingpadova.it., _dmarc.carsharingpadova.it."
fotovoltaico.apsopere.it,apsopere.it,True,False,,,False,,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[MX] In mx_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: fotovoltaico.apsopere.it. IN MX, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: fotovoltaico.apsopere.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: fotovoltaico.apsopere.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.fotovoltaico.apsopere.it., _dmarc.fotovoltaico.apsopere.it."
telerete.it,telerete.it,True,True,"mailftr3.telerete.it, mailftr3.telerete.it","25, 587, 465",True,mailftr3.telerete.it:25,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: telerete.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: telerete.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.telerete.it., _dmarc.telerete.it."
polizialocalepadova.it,polizialocalepadova.it,True,True,"mailftr3.telerete.it, mailftr3.telerete.it","25, 587, 465",True,mailftr3.telerete.it:25,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: polizialocalepadova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: polizialocalepadova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.polizialocalepadova.it., _dmarc.polizialocalepadova.it."
ne-t.it,ne-t.it,True,True,"mailftr3.telerete.it, mailftr3.telerete.it","25, 587, 465",True,mailftr3.telerete.it:25,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: ne-t.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: ne-t.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.ne-t.it., _dmarc.ne-t.it."
tribunaledipadova.it,tribunaledipadova.it,True,True,"mailftr2.telerete.it, mailftr1.telerete.it","25, 587, 465",True,"mailftr2.telerete.it:25, mailftr1.telerete.it:25",False,,False,False,,False,False,,False,False,,,,,,False,False,,"[STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 111] Connection refused, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 111] Connection refused, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 111] Connection refused, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 111] Connection refused, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: tribunaledipadova.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: tribunaledipadova.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.tribunaledipadova.it., _dmarc.tribunaledipadova.it."
padovawifi.it,padovawifi.it,True,True,"mailftr3.telerete.it, mailftr3.telerete.it","25, 587, 465",True,mailftr3.telerete.it:25,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovawifi.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: padovawifi.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.padovawifi.it., _dmarc.padovawifi.it."
cappelladegliscrovegni.it,cappelladegliscrovegni.it,True,True,"mailftr2.telerete.it, mailftr1.telerete.it","25, 587, 465",True,"mailftr2.telerete.it:25, mailftr1.telerete.it:25",False,,False,False,,False,False,,False,False,,,,,,False,False,,"[SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: cappelladegliscrovegni.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: cappelladegliscrovegni.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.cappelladegliscrovegni.it., _dmarc.cappelladegliscrovegni.it."
provincia.padova.it,provincia.padova.it,True,True,mbox.provincia.padova.it,"25, 587, 465",True,"mbox.provincia.padova.it:25, mbox.provincia.padova.it:587",True,"mbox.provincia.padova.it:25, mbox.provincia.padova.it:587",True,True,v=spf1 ip4:94.124.34.13 ip4:94.124.33.232 ip4:94.124.33.241 ip4:94.124.33.199 -all,False,False,,False,False,,,,,,False,False,,"[STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: Connection unexpectedly closed: timed out, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.provincia.padova.it., _dmarc.provincia.padova.it."
provincia.pd.it,provincia.pd.it,True,True,mbox.provincia.padova.it,"25, 587, 465",True,"mbox.provincia.padova.it:25, mbox.provincia.padova.it:587",True,"mbox.provincia.padova.it:25, mbox.provincia.padova.it:587",True,True,v=spf1 ip4:94.124.34.13 ip4:94.124.33.232 ip4:94.124.33.241 ip4:94.124.33.199 -all,False,False,,False,False,,,,,,False,False,,"[STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: Connection unexpectedly closed: timed out, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.provincia.pd.it., _dmarc.provincia.pd.it."
comune.padova.it,comune.padova.it,True,True,posta.comune.padova.it,"25, 587, 465",False,,False,,True,True,v=spf1 ip4:185.213.115.0/25 mx ~all,False,False,,False,False,,,,,,False,False,,"[STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: Connection unexpectedly closed: timed out, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: Connection unexpectedly closed: timed out, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 111] Connection refused, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.comune.padova.it., _dmarc.comune.padova.it."
apsholding.it,apsholding.it,True,True,"mailftr3.telerete.it, mailsrv3.telerete.it","25, 587, 465",True,"mailftr3.telerete.it:25, mailftr3.telerete.it:587, mailsrv3.telerete.it:25",False,,False,False,,False,False,,False,False,,,,,,False,False,,"[STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 111] Connection refused, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: timed out, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: timed out, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: apsholding.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: apsholding.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.apsholding.it., _dmarc.apsholding.it."
fsbusitaliaveneto.it,fsbusitaliaveneto.it,True,True,mail.fsbusitaliaveneto.it,"25, 587, 465",True,mail.fsbusitaliaveneto.it:25,False,,False,False,,False,False,,False,False,,,,,,False,False,,"[STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: timed out, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: timed out, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: fsbusitaliaveneto.it. IN TXT, [SPF] In get_spf_record_text at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:291: The DNS response does not contain an answer to the question: fsbusitaliaveneto.it. IN TXT, [DMARC] In dmarc_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:552: None of DNS query names exist: _dmarc.fsbusitaliaveneto.it., _dmarc.fsbusitaliaveneto.it."
arpa.veneto.it,arpa.veneto.it,True,True,"alt3.aspmx.l.google.com, alt4.aspmx.l.google.com, smtp.arpa.veneto.it, aspmx.l.google.com, alt1.aspmx.l.google.com, alt2.aspmx.l.google.com","25, 587, 465",True,"alt3.aspmx.l.google.com:25, alt4.aspmx.l.google.com:25, smtp.arpa.veneto.it:25, aspmx.l.google.com:25, alt1.aspmx.l.google.com:25, alt2.aspmx.l.google.com:25",True,"alt3.aspmx.l.google.com:25, alt4.aspmx.l.google.com:25, smtp.arpa.veneto.it:25, aspmx.l.google.com:25, alt1.aspmx.l.google.com:25, alt2.aspmx.l.google.com:25",True,True,v=spf1 ip4:213.217.132.52/32  include:_spf.google.com ~all,True,True,v=DMARC1; p=none; rua=mailto:info@arpa.veneto.it,True,True,v=DMARC1; p=none; rua=mailto:info@arpa.veneto.it,none,100,mailto:info@arpa.veneto.it,,True,False,,"[STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 101] Network is unreachable, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 101] Network is unreachable, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 101] Network is unreachable, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 101] Network is unreachable, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: timed out, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: Connection unexpectedly closed: timed out, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 101] Network is unreachable, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 101] Network is unreachable, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 101] Network is unreachable, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 101] Network is unreachable, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 101] Network is unreachable, [STARTTLS] In starttls_scan at /home/rampazzo/.local/lib/python3.6/site-packages/trustymail/trustymail.py:118: [Errno 101] Network is unreachable"
